### ISSUE TITLE
Golang编译错误找了很久，哪里设置错误了。

### ISSUE THREAD

**Issue by FlynnYork** [hslr-s/sun-panel#10]
环境，windows 11 64bit
报错，
lib\cmn\base.go:14:2: package sun-panel/assets is not in std (C:\Program Files\Go\src\sun-panel\assets)
复制了路径后提示下方错误了。
main.go:5:2: package sun-panel/global is not in std (C:\Program Files\Go\src\sun-panel\global)
main.go:6:2: package sun-panel/initialize is not in std (C:\Program Files\Go\src\sun-panel\initialize)
main.go:7:2: package sun-panel/router is not in std (C:\Program Files\Go\src\sun-panel\router)

**Comment by hslr-s** [comment]
go编译前，需要执行一个编译静态文件的操作，请参考：https://blog.enianteam.com/u/sun/content/211
按教程执行静态文件编译了吗？

**Comment by FlynnYork** [comment]
> go编译前，需要执行一个编译静态文件的操作，请参考：https://blog.enianteam.com/u/sun/content/211 按教程执行静态文件编译了吗？
请参考：https://blog.enianteam.com/u/sun/content/211

按照教程在service文件夹中生成了静态文件service/assets/bindata.go和service/bindata.go

```
$env:GO111MODULE="on"
cd service
go-bindata-assetfs -o=assets/bindata.go -pkg=assets assets/...
```
运行部署
`go run main.go`
运行提示下方，
`INFO    router/A_ENTER.go:39    Sun-Panel is Started.  Listening and serving HTTP on  #:3002`

windows浏览器打开localhost:3002提示404 page not found，这个是我编译位置有错吗？

**Comment by hslr-s** [comment]
前端文件是否手动编译了呢？我不知道你是否能看懂dockerfile文件，如果能看懂，大概看一下你应该就能明白

目前编译流程：
1. 先将前端文件编译得到`dist`文件夹，改名为`web`
2. 编译后端所需的静态文件
3. 然后`go build ...`

**Comment by FlynnYork** [comment]
> 前端文件是否手动编译了呢？我不知道你是否能看懂dockerfile文件，如果能看懂，大概看一下你应该就能明白
> 
> 目前编译流程：
> 
> 1. 先将前端文件编译得到`dist`文件夹，改名为`web`
> 2. 编译后端所需的静态文件
> 3. 然后`go build ...`

谢谢回复。已经运行成功了。后面想交叉编译成linux/arm64的时候弹出了错误，默认GOOS=windows，GOARCH=arm64编译正常。

```
$env:GOOS="linux"
$env:GOARCH="arm64"
$env:CGO_ENABLED=1
```
` go build -o sun-panel main.go`
```
# runtime/cgo
gcc_linux_arm64.c: In function '_cgo_sys_thread_start':
gcc_linux_arm64.c:22:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
  sigset_t ign, oset;
  ^~~~~~~~
  _sigset_t
gcc_linux_arm64.c:27:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_arm64.c:22:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors
```

**Comment by hslr-s** [comment]
带有cgo模块不支持交叉编译，需要特殊处理，我现在还没有找到一个好的解决方案。建议直接在你的arm设备上进行编译运行

**Comment by FlynnYork** [comment]
> 带有cgo模块不支持交叉编译，需要特殊处理，我现在还没有找到一个好的解决方案。建议直接在你的arm设备上进行编译运行

好的谢谢答复。这个项目很棒。

**Comment by hslr-s** [comment]
谢谢支持，后续我可能写一个自动编译的脚本，暂时缓解不懂代码的小伙伴在其他平台运行不了的问题
