### ISSUE TITLE
秀出你的导航站，相互交流学习下！

### ISSUE THREAD

**Issue by 80imike** [hslr-s/sun-panel#100]
我先来，下面是我的导航站，欢迎访问哟！

1. [ IT 人员必备工具箱 ](https://666666.dev/)

![](https://img.hi-linux.com/staticfile/19841708418505_.pic_hd-2024-02-21-RC5uqS.jpg)

**Comment by hslr-s** [comment]
非常全，超级棒的说😉。
但是这里是提bug和建议的区域。其他内容可以分享发布在[Discussions](https://github.com/hslr-s/sun-panel/discussions)，感谢支持！

**Comment by 80imike** [comment]
> 非常全，超级棒的说😉。 但是这里是提bug和建议的区域。其他内容可以分享发布在[Discussions](https://github.com/hslr-s/sun-panel/discussions)，感谢支持！

好的，我去这里发一下。
