### ISSUE TITLE
网址标签 无法在各个分组间 自由移动设置

### ISSUE THREAD

**Issue by tracy1949** [hslr-s/sun-panel#108]
网址标签 无法在各个分组间 自由移动设置  如图所示：
![Uploading QQ截图20240227105609.png…]()

**Comment by tracy1949** [comment]
https://llsky.eu.org/i/2024/02/27/65dd512a0bec6.png

**Comment by hslr-s** [comment]
请看：https://github.com/hslr-s/sun-panel/issues/99
