### ISSUE TITLE
请问，如何更改默认的 favicon.ico 呢？

### ISSUE THREAD

**Issue by 80imike** [hslr-s/sun-panel#109]
使用默认的 docker 镜像部署的，网站标题默认使用的是  sun-panel/public/favicon.ico  的这个 ico 。

因为是用的 docker 镜像直接换图标，会不太灵活，每次更新程序都必须手动在换一次

大佬，如果要更换为自己的，应该怎么做呢？能不能做一个功能支持下动态换 ico 和改默认的页签标题。

@hslr-s

**Comment by hslr-s** [comment]
#41
