### ISSUE TITLE
太好用了，希望增加 bing 壁纸API，同步必应的每日更新壁纸，主页就更完美了

### ISSUE THREAD

**Issue by tiancool** [hslr-s/sun-panel#122]
如题，感谢作者的付出！

**Comment by ym1123** [comment]
bing的壁纸api可以直接写入背景url里，我这里提供两个bing背景api供你使用，此issues可以关闭了
bing的随机壁纸：https://bing.img.run/rand.php
bing的每日壁纸：https://myhkw.cn/open/img/bing

**Comment by Wegamegit** [comment]
三四年前不是很流行随机api么。。。你直接添加个代码进自定义在下面就好了。比如楼上那位提供了地址<style>
body{background: url(https://myhkw.cn/open/img/bing) no-repeat;background-size:100% 100%;background-attachment:fixed;}
</style>

**Comment by ym1123** [comment]
![image](https://github.com/hslr-s/sun-panel/assets/112682753/282a5169-1226-49b1-a567-797241e3b5c8)
并不需要这么麻烦，在设置里面有使用url链接背景

**Comment by Wegamegit** [comment]
这样，刚接触我没研究，感谢解答

与末 ***@***.***> 于2024年3月15日周五 11:42写道：
