### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by guchengod** [hslr-s/sun-panel#13]
建议搞一个heimdall备份导入的功能，苦heimdall久已，奈何使用过久，有几百个，手动转移过于麻烦。

**Comment by hslr-s** [comment]
现在新版支持程序自身的图标配置导出导入，附加浏览器书签转换工具。暂时不计划为其他导航适配导出入功能。

如果你懂得代码并且愿意帮助他人，欢迎自己适配sun-panel的导入配置文件，并联系作者为你发布这个转换工具
