### ISSUE TITLE
[BUG] 自定义页脚显示图片有误，会自动换行

### ISSUE THREAD

**Issue by seamarks** [hslr-s/sun-panel#130]
**Version | 版本**
v1.3.0

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
以下是我的自定义页脚代码
```html
<div style="text-align: center;color:#fff">
    <a href="https://beian.miit.gov.cn" target="_blank">京ICP备 xxxxxxxxxx号</a>|<img src="https://s3.bmp.ovh/imgs/2024/03/17/d062cdd430f6afba.png" alt="备案图标.png"width="15" height="15"> <a href=\"https://beian.mps.gov.cn/#/query/webSearch?code=xxxxxxxxxx\">京公网安备xxxxxxxxxx</a><br>Powered By <a href="https://github.com/hslr-s/sun-panel" target="_blank" class="ml-[5px]">Sun-Panel</a></div>
</div>
``` 
正确的效果应是：
![screenshot-1710686353476](https://github.com/hslr-s/sun-panel/assets/162898005/70b71cd6-ef3e-468a-88ec-83324884e697)

实际效果是：
![screenshot-1710686473896](https://github.com/hslr-s/sun-panel/assets/162898005/dc42a023-bc7d-4585-84a0-820a536f587e)

**Comment by hslr-s** [comment]
自定义页脚已经开放，你说的这个问题需要自己适配
