### ISSUE TITLE
[Feature] 希望可以多台设备登录

### ISSUE THREAD

**Issue by Mydong** [hslr-s/sun-panel#160]
首先感谢作者大大提供这么好的项目。已经逐步将常用的信息迁移到面板中。🙏

由于现在限制1台设备登录。
导致现在电脑登录后，手机在登录，账号总是会被踢下去，然后重新输入账号和密码，很是不方便呢。
希望可以有多台设备登录的方式，可以参考memos或者视频软件例如腾讯视频等，有一个登录设备管理，当看到陌生设备踢掉就行了。

**Comment by hslr-s** [comment]
程序没有限制设备登录的。难道你说的是pro授权限制登录吗？

**Comment by Mydong** [comment]
> 程序没有限制设备登录的。难道你说的是pro授权限制登录吗？

刚刚测试了一下 还真是，登录上一台设备后，立马登录另外一台，不会提示。

看了下大家的反馈，应该是[#157 ](https://github.com/hslr-s/sun-panel/issues/157)   这个，登录会话过期的问题，


我说过一段时间，怎么总是需要重新登录，还以为是设备限制了
