### ISSUE TITLE
 docker.sock文件找不到

### ISSUE THREAD

**Issue by wintsa123** [hslr-s/sun-panel#178]
群晖的docker.sock文件不知道在哪，用find命令也找不到

**Comment by caxjm** [comment]
附议+1，谢谢！已充pro

**Comment by hslr-s** [comment]
正常是在：`/var/run/docker.sock`，不同系统或许有所不同，有的部分系统可能无法运行，可以到相关系统的论坛寻求帮助，并且可以把结果发到这里告知大家

**Comment by wintsa123** [comment]
/var/run/docker.sock
确实是这个文件，已经找到了
