### ISSUE TITLE
[BUG] 容器更新后面板无法自动适配更新后的容器

### ISSUE THREAD

**Issue by behinder85** [hslr-s/sun-panel#184]
**Version | 版本**
beta

**Environment | 运行环境**
docke

**Detailed description | 详细说明**
新版加入容器状态展示后
已有容器更新后
面板无法获取更新后的容器信息
应该是与容器ID绑定
但更新后容器ID变化便提示容器异常
希望自动更新容器ID以适配容器更新/重建/改名等一系列容器更换操作

**Comment by hslr-s** [comment]
已解决，请升级到`v1.5.2`
