### ISSUE TITLE
能否增加单个链接是否公开设置，目前只能分组 公开还是隐藏

### ISSUE THREAD

**Issue by chrisdong** [hslr-s/sun-panel#187]
能否增加单个链接是否公开设置，目前只能分组 公开还是隐藏

**Comment by chaomarks** [comment]
分组也没法设置吧，只能统一账号公开还是隐藏

**Comment by hslr-s** [comment]
暂时无计划，分组已经实现相关场景需求，做的过多会导致程序臃肿和易用性变得复杂

**Comment by hslr-s** [comment]
暂时无计划，分组已经实现相关场景需求，做的过多会导致程序臃肿和易用性变得复杂
