### ISSUE TITLE
缩小图标能否将系统状态图标除外

### ISSUE THREAD

**Issue by chaomarks** [hslr-s/sun-panel#191]
可否让这样显示
![image](https://github.com/hslr-s/sun-panel/assets/93130581/77276685-b0a5-404f-8720-ba33a6c58c1e)

**Comment by hslr-s** [comment]
最新的beta版本已经支持了。下个正式版本将彻底支持

**Comment by chaomarks** [comment]
感谢大佬， 希望可以添加单个分组公开时也和系统状态一样可选择是否显示
