### ISSUE TITLE
[能不能给分组加一个边栏?

### ISSUE THREAD

**Issue by baoyu0** [hslr-s/sun-panel#197]
亲呀，由于添加的网站挺多的呢，分组内容又是平铺开的哟，想要看分组就得下滑老长时间才能找到哇，可不可以给分组的名称加上一个边栏呀，那样就能方便直接点击相应分组就直接跳转过去咯。

**Comment by hslr-s** [comment]
综合考虑实用性，此功能以插件的形式来实现，请升级到`v1.5.2`，并[查看该插件](https://github.com/hslr-s/sun-panel-js-plugins/tree/master/toc)
