### ISSUE TITLE
[BUG] “自定义页脚”无法解析script标签输出的内容？

### ISSUE THREAD

**Issue by DuckDeng** [hslr-s/sun-panel#199]
**Version | 版本**
v1.4.0

**Environment | 运行环境**
eg: docker / ubuntu / windows
docker

**Detailed description | 详细说明**
“自定义页脚”无法解析script标签输出的内容。
eg.
`          <p>
            ©2020-
            <script>
              document.write(new Date().getFullYear());
            </script> MyName All rights reserved.
          </p>
`
这里的script标签应该被显示为`2024`，但实际情况是页脚并不包含`2024`这一部分，script标签被忽略了

**Comment by hslr-s** [comment]
已解决，请升级到`v1.5.2`
