### ISSUE TITLE
[BUG] v1.5.0，导航标题上方的留白变大了

### ISSUE THREAD

**Issue by ChenDY2233** [hslr-s/sun-panel#205]
**Version | 版本**
eg: v1.5.0

**Environment | 运行环境**
eg: docker

**Detailed description | 详细说明**
- 更新 `v1.5.0`后，由于登录功能按钮移动到右上角，导航标题上方的留白变大了
- 原本完整显示的卡片，需要向下滚动才能完整显示

![Snipaste_2024-07-11_23-14-08](https://github.com/hslr-s/sun-panel/assets/39426660/2e93c68f-9f79-4a8a-a2a8-8e9cd9e1de8d)

**Comment by hslr-s** [comment]
谢谢反馈，顶部间距可以在风格设置中修改的或者直接进入风格设置重置一下即可
![image](https://github.com/hslr-s/sun-panel/assets/38825747/87632f93-938e-47c5-806c-b757a05a75aa)
