### ISSUE TITLE
[BUG] 1.5.0版本标题不能水平居中了

### ISSUE THREAD

**Issue by adozhao** [hslr-s/sun-panel#206]
**Version | 版本**
v1.5.0

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
升级v1.5.0之后，如果没有描述好像不能把图标和名称水平居中了，难道是我姿势不对？  
![image](https://github.com/user-attachments/assets/27bc362c-5548-45af-8c04-a6713fdcfcef)

**Comment by Tan-xiaozi** [comment]
这个可以在”分组管理“对分组进行修改选择”隐藏描述信息“不然空值也会占用位置。

**Comment by Tan-xiaozi** [comment]
![Uploading WX20240712-144959@2x.png…]()

**Comment by adozhao** [comment]
> 这个可以在”分组管理“对分组进行修改选择”隐藏描述信息“不然空值也会占用位置。

感谢🙏，已搞定
