### ISSUE TITLE
docker v1.5.0 主页的拖拽排序失效

### ISSUE THREAD

**Issue by foxdodo** [hslr-s/sun-panel#208]
**Version | 版本**
v1.5.0

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
主页按“排序”按钮后将鼠标悬浮在图标上能出现十字形提示光标，但是按住左键无法拖拽。症状从1.4.0更新到1.5.0出现

**Comment by hslr-s** [comment]
已修复，直接更新 v1.5.1
