### ISSUE TITLE
[BUG] 容器卡片绑定的容器更新后显示异常

### ISSUE THREAD

**Issue by foxdodo** [hslr-s/sun-panel#211]
**Version | 版本**
v1.5.1

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
给alist-tvbox容器设置了容器卡片之后，如果每天定时更新容器则会在容器更新后出现卡片显示异常，似乎是因为卡片绑定的docker容器识别成了旧的容器ID，没有自动获取更新后的容器ID

**Comment by Nelson-Wcg** [comment]
确实，或者用容器的名称也可以。 更新后用相同的容器名称
期待作者回复

**Comment by hslr-s** [comment]
已解决，请升级到`v1.5.2`
