### ISSUE TITLE
[BUG] 公开模式无法固定搜索引擎

### ISSUE THREAD

**Issue by toseeu** [hslr-s/sun-panel#213]
**Version | 版本**
v1.5.1

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
自定义了搜索引擎，然后自己使用切换了自定义的搜索引擎。则公开用户就会使用自定义的搜索引擎。
自己因为其他原因切换了bing搜索。接着公开用户使用的就是bing搜索。

**Comment by toseeu** [comment]
希望能给公开用户设置一个固定的搜索引擎。或者允许公开用户自行切换其中的几种搜索引擎。

**Comment by hslr-s** [comment]
请升级到`v1.5.2`，未登录的公开模式下，支持切换搜索引擎（仅支持切换，不支持同步及记录当前搜索引擎的状态）
