### ISSUE TITLE
[BUG]容器卡片获取列表一直转圈，无法显示

### ISSUE THREAD

**Issue by yangbao93** [hslr-s/sun-panel#223]
**Version | 版本**

v1.5.1

**Environment | 运行环境**
eg: docker （黑群晖 N100 CPU）

**Detailed description | 详细说明**
使用 docker 容器卡片的时候，一直转圈，约三五分钟后转圈结束，docker 容器列表为空（实际不应该为空），且CPU 使用率会升高
![image](https://github.com/user-attachments/assets/2518572f-5f4a-4eb9-89dc-3b771dc4982f)
![image](https://github.com/user-attachments/assets/f05a91e5-f774-404e-8ec5-c4b6a6d4f248)

**Comment by ji1360677347** [comment]
8100t黑群，同版本，情况相同，也是卡在这里添加不了，既然能读取docker状态，希望作者能加一个一键导入所有容器的功能，感谢！

**Comment by Umfs** [comment]
我也遇到了相同的情况。群晖DS920+

**Comment by Umfs** [comment]
请问解决了吗？

**Comment by hslr-s** [comment]
已经在 `v1.5.2` 解决此问题
