### ISSUE TITLE
[Feature] Short description | 分类或者分组功能

### ISSUE THREAD

**Issue by baoyu0** [hslr-s/sun-panel#226]
于导航网站之中，可以规划出一个分类浏览窗格，将形形色色的网站链接加以分类。好比，可以把链接区分为 “生活”“影视”“软件工具” 等多个类目，让用户能够根据自身的需求快捷地寻找到想要的链接。

**Comment by hslr-s** [comment]
大概在`v1.2.0`以上就已经存在该功能了。用户可以根据自身需求新建分组
