### ISSUE TITLE
[BUG] 更新后，chrome内嵌框架打开异常

### ISSUE THREAD

**Issue by shiwentao1994** [hslr-s/sun-panel#228]
**Version | 版本**
v1.5.2

**Environment | 运行环境**
docker

**Detailed description | 详细说明**
主程序更新1.5.2版本后，chrome内嵌框架打开异常插件异常。在未登录状态下，右上角设置按钮无法点击。在登陆状态下，设置界面出错。已重装过chrome插件，问题依旧存在。

**Comment by shiwentao1994** [comment]
重新提交截图![屏幕截图 2024-08-28 194900](https://github.com/user-attachments/assets/244523b7-d7a2-4114-bde8-b6efa0a0c865)

**Comment by hslr-s** [comment]
清除一下缓存
