### ISSUE TITLE
建议作者还是重新换个logo比较好。。

### ISSUE THREAD

**Issue by L1mit1337** [hslr-s/sun-panel#233]
是不是水平翻转180 改个颜色就拿来用了
![image](https://github.com/user-attachments/assets/6eadf484-5589-42c4-9ed9-72fcd5b51321)

**Comment by L1mit1337** [comment]
https://zowiegear.benq.com.cn/

**Comment by hslr-s** [comment]
> 是不是水平翻转180 改个颜色就拿来用了
> ![image](https://github.com/user-attachments/assets/6eadf484-5589-42c4-9ed9-72fcd5b51321)
> 
> 

哈哈哈，只能说是同一种风格设计，不存在说翻转改颜色，sun-panel目前的logo也是由群里小伙伴重新优化来的。至于你说得这个品牌我也是现在才知道的
