### ISSUE TITLE
[Feature] Short description | 请问在有公网IP和域名的情况下如何实现HTTPS访问

### ISSUE THREAD

**Issue by zh8416** [hslr-s/sun-panel#240]
如题，我是拿群晖部署的sun-panel，访问端口是13002，在群晖里配置了反向代理访问的时候提示发送了无效的响应。域名和证书都是正常的，在配置文件里没发现有设置https端口的地方。

**Comment by Tan-xiaozi** [comment]
你应改去群晖的论坛问问，访问时候你要加https,而且群晖配置时候要配置成https访问，目的要设置为http

**Comment by zh8416** [comment]
> 你应改去群晖的论坛问问，访问时候你要加https,而且群晖配置时候要配置成https访问，目的要设置为http

感谢指点，确实是反向代理配置错了
