### ISSUE TITLE
[Feature] 能否支持更多环境切换

### ISSUE THREAD

**Issue by zhuweitung** [hslr-s/sun-panel#245]
**Is your feature request related to a problem? Please describe.**
目前支持外网和局域网两个环境切换
如果我有其他环境，比如tailscale、zerotier的虚拟局域网，就没办法在一个账号下切换大于2个环境

**Describe the solution you'd like**
在系统设置中增加自定义环境配置（图标和名称），在项目编辑中设置自定义环境地址

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by toseeu** [comment]
我有使用zerotier，zerotier可以设置网络转发。这样的话用局域网地址就好了。你是每个设备都添加zerotier吗？正常情况只有路由器设置zerotier，然后转发局域网吧。不太理解你这个需求的特殊场景

**Comment by zhuweitung** [comment]
> 我有使用zerotier，zerotier可以设置网络转发。这样的话用局域网地址就好了。你是每个设备都添加zerotier吗？正常情况只有路由器设置zerotier，然后转发局域网吧。不太理解你这个需求的特殊场景

我没有在路由器上安装，是在其他客户端安装的
我试下你说的方法看

**Comment by zhuweitung** [comment]
我用openp2p中虚拟网络的网络资源功能也实现了用局域网ip访问

**Comment by toseeu** [comment]
> > 我有使用zerotier，zerotier可以设置网络转发。这样的话用局域网地址就好了。你是每个设备都添加zerotier吗？正常情况只有路由器设置zerotier，然后转发局域网吧。不太理解你这个需求的特殊场景
> 
> 我没有在路由器上安装，是在其他客户端安装的 我试下你说的方法看

linux系统的话，修改`Sysctl`里边加参数

**Comment by toseeu** [comment]
> > 我有使用zerotier，zerotier可以设置网络转发。这样的话用局域网地址就好了。你是每个设备都添加zerotier吗？正常情况只有路由器设置zerotier，然后转发局域网吧。不太理解你这个需求的特殊场景
> 
> 我没有在路由器上安装，是在其他客户端安装的 我试下你说的方法看

linux系统的话，修改`Sysctl`文件，增加参数。 允许系统转发 IPv4 流量
```
net.ipv4.ip_forward = 1
net.ipv4.conf.all.src_valid_mark =1
```
