### ISSUE TITLE
[Feature] Short description | 简短说明,能否新增一个某个链接指定浏览器打开？

### ISSUE THREAD

**Issue by goode** [hslr-s/sun-panel#263]
由于工作需要，有些系统需要指定某版本的Chrome才能兼容，也有某些系统需要火狐，或者IE才能正常运行！希望可以的话可以增加一个链接指定浏览器打开！

**Comment by hslr-s** [comment]
网页受限于浏览器技术，无法实现跨浏览器打开地址
