### ISSUE TITLE
希望搜索栏支持内部书签搜索

### ISSUE THREAD

**Issue by leafney** [hslr-s/sun-panel#27]
已加群，试用了最新的beta版本，对于搜索功能有点想法。

目前的搜索是跳转搜索引擎，执行外网的数据搜索。感觉后期应该还会扩展其他功能吧，例如支持内部书签的搜索。

我目前想到的一种思路是可以为书签添加标签，通过支持标签来支持内部书签的搜索

例如我设置 `百度一下` 的一个标签为 `bd`，这样我在搜索栏中输入 `bd` 之后，下面就会展示出 `bd` 这个标签相关的已有书签，然后直接点击跳转。虽然说有分类功能，但分类或书签添加太多了之后找起来也是要花一定时间的。

对于搜索栏的内部搜索和外网搜索的切换，例如可以通过使用 `tab`键或支持自定义快捷键来实现快速切换。

**Comment by gitlyp** [comment]
支持 title url 描述 搜索你可以体验看看有没有啥问题
非官方版  升级方法 按群主说的来
dockerliaocn/sun-panel:1.1.0-beta23-11-29
