### ISSUE TITLE
每次开浏览器都要登录,不加上记住帐号功能吗

### ISSUE THREAD

**Issue by woiplmm** [hslr-s/sun-panel#272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
每次开浏览器都要登录,不加上记住帐号功能吗

**Comment by simaek** [comment]
复议

**Comment by Tan-xiaozi** [comment]
只要登入了不退出 不是不会每次都要登入吧

**Comment by simaek** [comment]
> 只要登入了不退出 不是不会每次都要登入吧

看过了，token没有存Cookie，浏览器退出了，会话就结束了，需要重新登录。

而且现在又闭源了，我想自己改也没有办法。

**Comment by Tan-xiaozi** [comment]
> > 只要登入了不退出 不是不会每次都要登入吧
> 
> 看过了，token没有存Cookie，浏览器退出了，会话就结束了，需要重新登录。
> 
> 而且现在又闭源了，我想自己改也没有办法。

为啥我没这样，我登入一次后 退出浏览器也没有发现第二次需要登入

**Comment by hslr-s** [comment]
目前是每次登录，会话都会延续7天有效期，也就是说只要你登录一次，7天内再次访问页面就永远不会过期。如果仍然出现每天/次都会过期的情况，请检查是不是存在以下情况

1. 浏览器是不是设置了每次退出都会清除数据
2. 是不是在浏览器的无痕模式下使用的项目
3. 项目部署端是不是有被重启过，项目每次重启所有的登录会话都会失效

如果以上都不存在，请进一步反馈

如果上述的1，2在你的使用环境中不可以避免，可以在项目的账号管理设置一个公开账号，设置后仅在修改数据的时候才需要登录。

如果上述3也是无法避免的，可以设置使用redis来作为缓存，具体可以参考项目的配置文件
