### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by suqin1020** [hslr-s/sun-panel#3]
1. 导航页可不可以去掉登陆直接浏览？  
2. 设置一些必须登陆才能看到的网页？  
3. 增加分组设置  
4. 当切换到内网模式时只显示有内网地址的网址会不会更好。

**Comment by hslr-s** [comment]
1. 准备这次做，3.准备以后研究一个方案后做，4.暂不做，用户需求不同，也不能确保在内网模式不访问外网地址
