### ISSUE TITLE
[Feature] 搜索框新增针对页面应用搜索功能

### ISSUE THREAD

**Issue by oubayun** [hslr-s/sun-panel#31]
**Is your feature request related to a problem? Please describe.**

目前搜索框是基于搜索引擎进行搜索，希望能够针对页面本身应用图标名称等进行搜索，因为可以会有很多标签图标。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tan-xiaozi** [comment]
假如想所搜的东西，刚好的图标名重合，岂不是很尴尬，个人意见

**Comment by shadowwalker-xu** [comment]
> 假如想所搜的东西，刚好的图标名重合，岂不是很尴尬，个人意见

当图标过多时，还要一个一个的去页面找吗？
