### ISSUE TITLE
[建议] Docker映射目录精简为1个

### ISSUE THREAD

**Issue by jackloves111** [hslr-s/sun-panel#32]
只保留config，其他的诸如上传和数据库，可以都放在config里面，项目本身体积不会很大

**Comment by jackloves111** [comment]
docker run -d --restart=always -p 3002:3002 \
-v ~/docker_data/sun-panel/conf:/app/conf \
-v ~/docker_data/sun-panel/uploads:/app/uploads \
-v ~/docker_data/sun-panel/database:/app/database \
--name sun-panel \
hslr/sun-panel

精简为

docker run -d --restart=always -p 3002:3002 \
-v ~/docker_data/sun-panel/config:/app/config \
--name sun-panel \
hslr/sun-panel

**Comment by jackloves111** [comment]
![IOH@)E@WHMPKSFGTTUH H90](https://github.com/hslr-s/sun-panel/assets/89971817/7cac813a-4f0c-4166-9362-079bfab73ece)
用户只要映射config就可以了，里面的三个文件夹，不用用户单独去映射的

**Comment by editwe** [comment]
复议

**Comment by editwe** [comment]
附议

**Comment by aisyun** [comment]
这个个人感觉意义不大，目录多也是更精细

**Comment by editwe** [comment]
> 这个个人感觉意义不大，目录多也是更精细

配置的时候可以省点事情，只需要配置一个目录即可

**Comment by hslr-s** [comment]
多谢建议，最新beta版本已经实现，感兴趣的话可以提前尝鲜或者等待正式版本的发布
