### ISSUE TITLE
可以提供一个webhook接口么，当ip端口变动时，可以调用webhook接口，动态改变需要跳转的地址

### ISSUE THREAD

**Issue by caiwenmin** [hslr-s/sun-panel#36]
提供一个webhook接口，nat打洞用户，公网端口是随机的，且随时可能变动，希望可以通过webhook实现通知导航页更新访问路径

**Comment by hslr-s** [comment]
[目前已经提供了](https://doc.sun-panel.top/zh_cn/openapi/v1/apis.html)
