### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by chaiguifeng007** [hslr-s/sun-panel#4]
打开即用，不要登录；
需要修改再登录，可以加个/admin后缀

**Comment by waxnx** [comment]
登录有登录好处吧。由于我会把nas上的一些东西放上去方便自己用，尤其是如果临时用其他人电脑登录的话这样会好一些。（虽然可以通过npm设置规则来实现账号和密码的验证）目前在用的一个导航今天刚更新的就是设置不同账户的功能。

**Comment by chaiguifeng007** [comment]
好吧，我先这样用用看；
今天运行起来了。
能不能加个分组功能呢？就像homepage那样的。
最后，谢谢大公无私开源。

**Comment by Tan-xiaozi** [comment]
我感觉呢，在菜单栏里面设置一个管理员登入的入口就行

**Comment by hslr-s** [comment]
我对大家的管理员模式有个疑问，两个方案
1.  多账号可以看到一个桌面，管理员才有编辑权限
2.  还是每个账号有一个桌面，然后每个账号单独管理各自桌面，然后需要一个超级管理员权限的账号

**Comment by Tan-xiaozi** [comment]
> 我对大家的管理员模式有个疑问，两个方案
> 
> 1. 多账号可以看到一个桌面，管理员才有编辑权限
> 2. 还是每个账号有一个桌面，然后每个账号单独管理各自桌面，然后需要一个超级管理员权限的账号

突然想起了一个事情
一是，作者的项目是每个账号可以单独设置，也就是说是账户的相互独立，那么最开始进入时候必须得进行登入，因为只有登入后，软件才知道谁使用，显示什么东西，既然必须最开始登入，那么最开始就是管理员模式，顶多设置一个编辑开关，而这个开关可以通过验证密码方式去切换；
二是，访客模式是不许要输入密码就能够访问的，那么只能有一个桌面，也就是只能有一个账户，也就是作者的第一个方案，
三是，我想请问作者以及大家，多账户模式是否需要，因为可以随时切换不同的风格，不同的排序，我觉得是否可以添加配置列表，由管理员去选择配置，来切换不同的排序、风格、页面、数量。
以上是我看到作者的方案所思索的东西，如有错误还请指出。

**Comment by Tan-xiaozi** [comment]
> 我对大家的管理员模式有个疑问，两个方案
> 
> 1. 多账号可以看到一个桌面，管理员才有编辑权限
> 2. 还是每个账号有一个桌面，然后每个账号单独管理各自桌面，然后需要一个超级管理员权限的账号

第一个方案只有一个桌面，这个也是现在很多导航项目所用的模式，这个也是比较容易做访客的机制的方案，第二个方案是否是默认进入访客账户，然后能在菜单里面去切换账户以此来显示不同的桌面，这样只需要对访客账户设置编辑开关就行，但是这样访客显得很费，毕竟来说这个项目也不会公开在公网上使用，也就是个人使用，我认为第一个方案比较靠谱，然后再第一个方案里面添加桌面配置列表，以此来选择不同的桌面。
