### ISSUE TITLE
站点自身图标修改，添加图标界面记住上次选择项

### ISSUE THREAD

**Issue by ausmas** [hslr-s/sun-panel#41]
添加图标时最好能记住分组、图标类型、打开方式的上次选择内容。
站点自身图标目前不可修改，建议增加修改项。

**Comment by hslr-s** [comment]
可以通过挂载docker文件的方式来实现站点图标的更换，

挂载一下两个图标文件即可：

-v 图标的绝对路径:/web/favicon.ico
-v 图标的绝对路径:/web/favicon.svg

**Comment by NiaoBlush** [comment]
我挂载到 `/web` 下没有成功, 
后来挂载到 `/app/web`下成功修改了站点图标

```
-v 图标的绝对路径:/app/web/favicon.ico
-v 图标的绝对路径:/app/web/favicon.svg
```

**Comment by sicifus** [comment]
我再补一个飞牛原生Sun-Panel应用（非docker）的解决办法，
很简单，把ico文件（文件名任意）传到自己指定的文件夹中，并设置好权限，
然后在应用中心 -> Sun-Panel -> 应用设置里，添加相应的文件夹，
就能自动识别出来favicon了
