### ISSUE TITLE
[Feature] 希望Sun-Panel能加入反代功能

### ISSUE THREAD

**Issue by X7A600** [hslr-s/sun-panel#43]
### 建议描述
在国内，电信运营商限制了对公网的访问，并且内网穿透通常只提供一个端口。因此，在Sun-Panel上增加一个新功能将会很有用：允许将特定服务的网页反向代理到二级目录，以便通过内网穿透访问。
比如说 "http://Sun-Panel.com/ikuai" 这样的

### 功能需求
**反向代理功能**： 能够将特定服务的网页反向代理到指定的二级目录，以便通过内网穿透访问。比如说使用Nginx?
**定制性**： 允许用户自定义需要反向代理的服务和对应的二级目录。
**易用性**： 在导航面板中提供简单直观的界面，也许是一些默认配置，比如说alist、爱快这些常用的配置可以选择，让用户能够轻松配置反向代理规则。

### 预期效果
通过这个功能，用户可以单一访问Sun-Panel就可以管理局域网内的所有服务，同时提升了Sun-Panel的灵活性和实用性。

**Comment by hslr-s** [comment]
好点子这两天正在研究，谢谢建议

**Comment by aisyun** [comment]
可以使用nginx做反代
如果集成到sun-panel里显得过于臃肿。也不是什么大痛点，或必须

**Comment by chrisdong** [comment]
lucky安装后，就可以实现，比nginx要容易太多了。 不要在sun-panel里加这个功能，不然就臃肿了。
cloudflare 绑定 xxx.eu.org的二级域名在lucky 上可以申请ssl证书，能自动延期。
dynv6的二级ddns域名也支持在lucky上申请ssl证书。
自己购买的域名更能支持ssl在lucky上使用。
在web服务里，利用前面绑定的域名，可以做 反向代理。

**Comment by hslr-s** [comment]
目前可以搭配`Sun-Proxy`+`frp`,[这是教程](https://doc.sun-panel.top/zh_cn/advanced/use_reverse_proxy.html)
