### ISSUE TITLE
期望增加一个一个小功能：增加子账号功能 子账号只可以使用 不可以修改链接图标之类的。

### ISSUE THREAD

**Issue by wincol1151** [hslr-s/sun-panel#46]
你这个导航面板 我绝对非常好 尤其是未来可以自定义搜索 。我想向你提出一个小需求 ，就是是否可以增加一个子账号功能，该子账号只可以使用面板的app  但是不能修改里面的设置，比如链接，图标什么的 。  多谢了

**Comment by Hopers** [comment]
访客账号？那你只输入用户名，密码留空不就成了

**Comment by ym1123** [comment]
下一个正式版本会有访客功能和导入导出功能，您可以非常方便的复制各个账户之间的内容，并用访客模式代替子账号来使用。
