### ISSUE TITLE
1.2.0改成强制自适应界面了么？

### ISSUE THREAD

**Issue by WYithal** [hslr-s/sun-panel#48]
** Version | 版本 **
v1.2.0

** Environment | 运行环境 **
docker

** Detailed description | 详细说明 **
4K屏，系统缩放150%，浏览器100%

升到1.2.0搜索框很长一条，图标布局会随浏览器大小自适应变化，好像也没找到哪里设置改回1.2.0版本之前的布局

<img width="1046" alt="Snipaste_2023-12-28_22-07-50" src="https://github.com/hslr-s/sun-panel/assets/13925273/be894de8-612b-4acd-91fd-522ba1efe59d">

**Comment by hslr-s** [comment]
当前设计如此。更新到v1.2.1支持设置内容区域的最大宽度，来实现之前版本的效果
