### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Tan-xiaozi** [hslr-s/sun-panel#6]
直接说了
1、添加“访客“功能，可以直接打开。不需要登入，只能看到访客才能看到的内容；
2、添加”管理员“选项，在右下角的菜单栏添加管理员登入选项，只有进入管理员才能有编辑权限，同时能看到一些管理员才能看到的分组；
3、添加”编辑模式开关“在右下角的菜单栏添加编辑模式开关选项，管理员状态下，只有打开编辑模式才能编辑，这样可以防止误修改；
4、添加”分组“功能，可以建立分组，同时可以设置分组的权限，是否属于私有分组；
5、添加”权限“功能，可以对分组、进行权限设置，因为对单个网页去分配权限排版比较麻烦，分组却比较方便；
6、添加”拖拽“通过鼠标拖拽更加方便调整位置。
以上是我个人的建议，也是我个人对项目的理解，若有冒犯，请包涵。

**Comment by Tan-xiaozi** [comment]
同时感谢作者，开发一套符合国人的审美的导航项目

**Comment by bansi707754719** [comment]
也是有这个需求，你总结建议得更到位。感谢导航的作者。
