### ISSUE TITLE
[Feature] Short description |  图标复用

### ISSUE THREAD

**Issue by HU914** [hslr-s/sun-panel#65]
新建标签时：
1、新增一个图标库选项，图标库指向已上传的图标文件夹
2、该功能可对已上传的图标进行重复利用。

问题：
使用新建标签时，我想用同一个图标，但我每次都需要上传，如果能够让我选择已上传过的图标，能够更加便捷

**Comment by 80imike** [comment]
这个可以有，支持

**Comment by wyhghost** [comment]
现在是可以实现的，在设置里的上传文件管理可以查看文件路径，复制下来。
然后设置图标时直接输入这个图标地址就行了
