### ISSUE TITLE
增加图标缓存，无需每次从url加载

### ISSUE THREAD

**Issue by qq77522980** [hslr-s/sun-panel#74]
图标缓存到本地，定时自动重载或者手动都可以，可以避免有时图标加载很久或者部分加载不出来要重新刷新的情况。

**Comment by 80imike** [comment]
支持，图标每次重新加载很费时间，会引起网页打开慢

**Comment by hslr-s** [comment]
图标不应该是自动缓存的吗，请提供更多有效和截图，并告知图标格式

**Comment by qq77522980** [comment]
![1706087852957](https://github.com/hslr-s/sun-panel/assets/74188271/d9a9e7d9-76f5-4c47-b215-94796730c9d2)
主要是重新登录的时候，链接图标会动态从url加载，我的意思是如果加载成功后就缓存到服务器里，不必重新加载就好了。

**Comment by qq77522980** [comment]
![image](https://github.com/hslr-s/sun-panel/assets/74188271/4b0ec116-0cf0-412e-af01-d8b988a515ec)
比如，这个图标，是从源地址https://alist.nn.ci/logo.svg加载的，我的意思是，如果第一次加载后，就保存到服务器本地，以后就显示服务器本地的图标。

**Comment by sesame-foxes** [comment]
手动下载后上传
