### ISSUE TITLE
[BUG] 群晖内存显示不正确

### ISSUE THREAD

**Issue by m1732948116** [hslr-s/sun-panel#85]
**Version | 版本**
v1.3.0

**Environment | 运行环境**
群晖docker

**Detailed description | 详细说明**
显示内存（2g）为物理内存（4g）的一半大小，但已用内存的比例正确。
sun-panel：
![内存显示错误](https://github.com/hslr-s/sun-panel/assets/66426989/b876698d-a358-4f6e-a97b-c3b67b36ef12)
群晖：
![实际内存](https://github.com/hslr-s/sun-panel/assets/66426989/49609ce4-66b9-4f6e-ba94-dfe0cbdb7692)

**Comment by hslr-s** [comment]
目前显示的方式是：已用/未使用，后续可能进行优化
