### ISSUE TITLE
支持AD/LDAP驗證

### ISSUE THREAD

**Issue by Phreeman33** [hslr-s/sun-panel#89]
如果能支持AD/LDAP驗證功能，搭配外部SSPR，就不需要管理員手動建立及管理其他帳號了

**Comment by liandu2024** [comment]
这个，难道自己家里的NAS也装了AD域控制器？

**Comment by Phreeman33** [comment]
> 这个，难道自己家里的NAS也装了AD域控制器？

用的TrueNAS Scale，因為其他使用者太常忘記帳號密碼，總要管理員手動重置密碼，索性建置Samba AD加PWM實現使用者自主管理帳號密碼。
可惜國內沒找到合適的教程，當初費了好大勁胡亂摸索才搞定；好在配置完後還是挺好用的，很多開源軟件都有支援AD/LDAP驗證，連接好AD服務器後就不需再配置一遍帳號密碼。

會提這個需求主要是看到Homarr宣佈很快就要實做LDAP功能，可見這需求應該還是有的。

**Comment by liandu2024** [comment]
> > 这个，难道自己家里的NAS也装了AD域控制器？
> 
> 用的TrueNAS Scale，因為其他用戶太常忘記帳號密碼，總要管理員手動重置密碼，索性建置Samba AD加PWM實現用戶自主管理帳號密碼。 可惜國內沒找到合適的教程，當初費了好大勁胡亂摸索才搞定；好在配置完後還是挺好用的，很多開源軟件都有支援AD/LDAP驗證，連接好AD服務器後就不需再配置一遍帳號密碼。
> 
> 會提這個需求主要是看到Homarr宣佈很快就要實做LDAP功能，可見這需求應該還是有的。

NAS 应用支持 LDAP 的怕一半都不到吧？
不是LDAP不好，而是现实就是这样，说实在的在公司里面，完全统一账户都很难。
