### ISSUE TITLE
能否根据内外网链接设置情况，动态显示图标！！！

### ISSUE THREAD

**Issue by thgslz** [hslr-s/sun-panel#90]
我的一些应用是只有内网链接，没有外网链接。

在现有系统功能下，添加一个图标时，外网链接位置不能为空。要是添加的话，我只能是把外网链接设置为“#”。

能否在本系统中添加一个功能，就是当用户点击内外网切换时，系统动态显示图标。例如:当用户点击切换内网时，只显示设置了有效内网链接的图标才被显示。

**Comment by hslr-s** [comment]
谢谢你的建议。当仅有一个网站的时候，就把地址填入第一个地址栏。程序就是这样设计的，可以到文档的[常见问题](https://doc.sun-panel.top/zh_cn/faq/faq.html)看一下作者设计初衷
