### ISSUE TITLE
去掉标题、自定义行间距

### ISSUE THREAD

**Issue by liandu2024** [hslr-s/sun-panel#91]
![PixPin_2024-02-08_11-36-45](https://github.com/hslr-s/sun-panel/assets/155928686/ab3de3d8-1b89-4670-9825-9f1725f65351)
这个导航软件写的非常棒，但有以下建议，望采纳：
1、最上面标题及时间，但对很多人来说，可能没有实际意义，希望能增加一个选项，可以不显示 标题及时间，可以节约一大堆空间。
2、分组的间距以及行间距，最好能自定义，这样，也能节约一大堆空间。

**Comment by hslr-s** [comment]
以上提到的标题时钟会在长期计划中实现，暂时可以通过自定义css或者页脚填写样式代码来实现

**Comment by liandu2024** [comment]
> 以上提到的标题时钟会在长期计划中实现，暂时可以通过自定义css或者页脚填写样式代码来实现

感谢作者回复，能否给出一段“去掉标题”、“减少间距”的示例css代码？

**Comment by emtry** [comment]
> > 以上提到的标题时钟会在长期计划中实现，暂时可以通过自定义css或者页脚填写样式代码来实现
> 
> 感谢作者回复，能否给出一段“去掉标题”、“减少间距”的示例css代码？

<style>
  .flex.mx-\[auto\].items-center.justify-center.text-white { display: none; }
  [data-v-679daf12].mt-\[50px\] { margin-top: 0px !important; }
  [data-v-f21ede0f].mt-\[50px\] { margin-top: 20px !important; }
</style>

**Comment by liandu2024** [comment]
搞定了！非常感谢！

**Comment by emtry** [comment]
> 搞定了！非常感谢！

<style>
  .flex.mx-\[auto\].items-center.justify-center.text-white { display: none; }
  [data-v-679daf12].mt-\[50px\] { margin-top: 0px !important; }
  [data-v-f21ede0f].mx-auto { margin-top: 20px !important; }
  [data-v-f21ede0f].mt-\[50px\] { margin-top: 20px !important; }
</style>

**Comment by liandu2024** [comment]
现在还剩一小点问题，就是 图标折行 后，行间距还是太大，不太美观，能再给段代码 缩小下间距吗？感谢！
<img width="1195" alt="Snipaste_2024-02-22_17-58-54" src="https://github.com/hslr-s/sun-panel/assets/155928686/c1a8f993-d25b-4b78-ac6e-e10430175513">
