### ISSUE TITLE
[Feature] 关于构建 docker 镜像 workflow 的建议

### ISSUE THREAD

**Issue by ngc7331** [hslr-s/sun-panel#93]
## 引入 beta 标签和大版本标签
刷 b 站看到有评论讲希望在不手动修改版本号的情况下一直体验最新版本。想到类似的需求还有固定在某个大版本的最新版，避免 breaking changes

目前的标签只有每个版本自己的版本号，以及 latest 指向最新正式版，并不能满足上述需求，因此建议引入：
- `x`：指向 `x.y.z` 的最新正式版
- `x.y`：指向 `x.y.z` 的最新正式版
- `edge`/`nightly`：指向最新的 beta **或**正式版
- `beta`：指向最新的 beta 版（也许没有必要，因为可能落后于正式版）

要改的应该只有两个 .yml 文件最后的`tags`，以及 README 里要加点说明，有需要的话我可以稍后提个 pr

## workflow 触发条件
在考虑前面的问题时顺便 review 了一下现在的 workflow 定义，注意到正式版和 beta 版的构建用的触发条件是一样的？
https://github.com/hslr-s/sun-panel/blob/917397bcf6af1ebf10c2c74f1586b5761996a4ea/.github/workflows/docker-build-push.yml#L3-L7

是把 beta 版触发的正式版构建流程给人工取消掉了吗 orz

参考[官方文档](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)，建议把两者的触发条件分别改为
```yml
tags:
  - 'v[0-9]+.[0-9]+.[0-9]+'
```
和
```yml
tags:
  - 'v[0-9]+.[0-9]+.[0-9]+-beta*'
```

如果这个规则太严格没有必要，也可以考虑
```yml
tags:
  - 'v*'
  - '!v*-beta*'
```
和
```yml
tags:
  - 'v*-beta*'
```
这种写法，按现在的 tag 命名规则应该是没啥问题

**Comment by hslr-s** [comment]
谢谢你的提议
