### ISSUE TITLE
强烈建议：加上跨分组移动项目功能，需要的进来支持下吧！

### ISSUE THREAD

**Issue by 80imike** [hslr-s/sun-panel#99]
有很多时候，需要将之间增加好的项目调整到新增的分组中。目前只能手动在新的分组重新加一次，强烈建议增加上跨分组移动项目这个功能。相信这个需求，很多朋友都需要吧！

下面是我的导航站，欢迎访问哟！

[IT 人员必备工具箱](https://666666.dev/)

**Comment by hslr-s** [comment]
右键编辑图标第一项可以更改分组，不需要新建组重复添加

**Comment by 80imike** [comment]
> 右键编辑图标第一项可以更改分组，不需要新建组重复添加

感谢大佬回复，没注意这里可以选，666 ！
